magephp:
  environments:
    production:
      ssh:
        port: 22
        flags: -i ~/.ssh/ka_id_rsa -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
      user: root
      branch: master
      from: ./
      host_path: /var/www/kiev-adventures
      exclude:
        - ./var/cache/*
        - ./var/log/*
        - ./web/app_dev.php
      hosts:
        - kiev-adventures.com
      pre-deploy:
        - git/update
#        - composer/install
#        - composer/dump-autoload
      on-deploy:
        - symfony/cache-warmup: { env: 'prod' }
        - symfony/assets-install: { env: 'prod' }
#        - symfony/assetic-dump: { env: 'prod' }
        - fs/copy: { from: 'app/config/parameters.prod.yml', to: 'app/config/parameters.yml' }
      on-release:
      post-release:
      post-deploy:
        - exec: { cmd: './post-deploy.sh', desc: 'Setting file rights' }