imports:
    - { resource: security.yml }
    - { resource: ../config.yml }

# SymfonyCMF Configuration
cmf_routing:
    chain:
        routers_by_id:
            router.default: 100
            cmf_routing.dynamic_router: 20
    dynamic:
        enabled: true
        route_provider_service_id: sulu_website.provider.content

# Exception Controller
fos_rest:
    exception:
        enabled: false # temporary fix for the exception controller until FOSRestBundle is updated to 2.0

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
        uglifycss:
            bin: /usr/local/bin/uglifycss


